image: Ubuntu1804  # образ для сборки

stack: node 16  # окружение

branches:
  only:
    - master  # ветка git

cache: node_modules  # кеширование

install:
  - npm install  # команда установки зависимостей

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - npm run build   # команда сборки

deploy:  # скрипт развёртывания
  - provider: GitHub
    description: 'DOM3'
    auth_token:
      secure: QYZ9IfLbWsraZNIUoRKWrVdb88S+dQjOhZQVjV59WplVkQDWaI8Cqt44Q/1TXxUZ
    draft: false
    prerelease: false
    force_update: true
    on:
      branch: master
