image: Ubuntu1804  # образ для сборки

stack: node 16  # окружение

branches:
  only:
    - master  # ветка git

cache: node_modules  # кеширование

install:
  - npm install  # команда установки зависимостей

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - npm run build   # команда сборки

deploy:  # скрипт развёртывания
  description: 'DOM3'
  provider: GitHub
  auth_token:
    secure: $(GITHUB_TOKEN)
  draft: false
  prerelease: false
  on:
    branch: master
